### ISSUE TITLE
golang wasm VM

### ISSUE THREAD

**Issue by gedw99** [maxmcd/wasm-servers#3]
Not sure if this is aligned with your goals but figured its worth mentioning this.
Its 100% golang based and they also have a AOT compiler too for the WASM from what i can see.

Cloud ABI looks pretty interesting too but is a long way off still. Perlin Noise being all golang sort of makes things quicker to get going and another alternative.

https://github.com/perlin-network

also runs on mobiles
https://github.com/perlin-network/life/pull/56

**Comment by maxmcd** [comment]
Thanks for the suggestion :)

I actually started with Life, but ran into this bug: https://github.com/perlin-network/life/issues/42#issuecomment-444156162

Life is also an interpreter (a fast interpreter), but it's not compiling the wasm instructions to assembly so it is a bit slower than https://github.com/CraneStation/cranelift

Cranelift (through https://github.com/CraneStation/wasmtime/ and wasmer) works today, and it's quite nice.

**Comment by maxmcd** [comment]
Ah, whoops, they are getting ahead-of-time compilation: https://github.com/perlin-network/life/pull/55
Very Interesting.

**Comment by losfair** [comment]
https://github.com/perlin-network/life/pull/55 is merged now.

Issue https://github.com/perlin-network/life/issues/42 is related to value slot allocation for interpreter being done incorrectly and we are investigating the issue at the moment. This problem doesn't exist with the AOT compilation.

**Comment by maxmcd** [comment]
@losfair that's awesome!
